### ISSUE TITLE
Inssuficent permission

### ISSUE THREAD

**Issue by Matthis2909** [GoogleCloudPlatform/gke-managed-certs#16]
Hi ! When I'm logging inside `managed-cert` pod I have this

`googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes.`

Is it a bug or just miss configuration ?

**Comment by bmhatfield** [comment]
Peep this bug I filed: https://github.com/GoogleCloudPlatform/gke-managed-certs/issues/14

**Comment by krzykwas** [comment]
Please see the README for permissions setup guide.
