### ISSUE TITLE
Rebase gke-certificate-controller image to distroless

### ISSUE THREAD

**Issue by yuwenma** [GoogleCloudPlatform/gke-managed-certs#17]
As part of the effort described in [KEP:Rebase images to distroless](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md), we need to rebase gke-certificate-controller image to distroless.

The action items include:
1. Replace glog to klog in the source code.
2. Remove shell dependencies in Dockerfile:
  run.sh pipes the stdout and redirects the log to /var/log/managed_certificate_controller.log. After klog is applied, we can use klog flag "--log-file=/var/log/managed_certificate_controller.log" to replace the shell cmd and then no bash script is required.

**Comment by yuwenma** [comment]
/cc @michallowicki 
/cc @krzykwas
This effort is targeting v1.15 (around Jun). Can you help finding a good owner?

**Comment by krzykwas** [comment]
This repo only exposes gke-internal repo publicly, so any changes need to be made there first. I'm sure we don't have to discuss priorities for this and other projects publicly. Please reach out to mbwalas@ for prioritization.

**Comment by krzykwas** [comment]
This effort is tracked internally to Google, closing this thread.
