### ISSUE TITLE
Add a BIG warning saying most people don't need to follow Install instructions

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/gke-managed-certs#19]
It seems like Install instructions in the readme is for a very small % of the people trying to run "Kubernetes on GCE". Is that right?

If I'm on GKE, I can be easily misled by the readme in this repo and may try to apply CRD/controller myself –which is a bad idea. Can you please prevent this from happening.

A good way to achieve this could be:

1. add a big warning saying people not to follow installation instructions and follow the docs instead
2. move the install instructions out of root README.

**Comment by jjhuff** [comment]
Was this a recent change for GKE?  I set this up recently, and I thought that the docs called for installing the CRD&controller from this project.

They don't now: https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs

Perhaps the docs for this project should point GKE users to the above URL as well.

**Comment by ahmetb** [comment]
@jjhuff I'm not sure but I think you're not supposed to install anything from this repo manually if you're on GKE anymore.
@krzykwas to confirm soon.

**Comment by jjhuff** [comment]
Well, that's definitely progress in making this easier.
Is simply deleting the CRD and controller likely to be safe on an existing cluster?

**Comment by ahmetb** [comment]
Not sure.  But the fact that you’re asking these questions make me believe that the installation instructions should not exist on this repository so visibly.

**Comment by bmhatfield** [comment]
Wow! This is a super timely issue, thanks for filing this @ahmetb. Like @jjhuff, I recently set this up as well. Should I delete it from my cluster? What version of K8S is required for this to be available?

**Comment by aav7fl** [comment]
I see we're all looking at the same documentation as well today. 

@bmhatfield I updated my cluster to `1.12.6-gke.10` per the mention of having it at least `1.12.6-gke.7` [here](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#creating_an_ingress_with_a_managed_certificate).

**Comment by bmhatfield** [comment]
Oh! I totally missed that line. Perfect! Thank you!

**Comment by bmhatfield** [comment]
@aav7fl are you having any luck with this? I upgraded and can confirm that `managedcertificates` is  available (both in a cluster that never had this deployed, as well as one that did).

However... nothing happens. The ingress is created, but only with an HTTP frontend. No certificate is obtained, no events are created, the ManagedCertificate doesn't have a status, and there's no indications of errors or progress. It's almost as if the controller isn't running in the cluster.

Did anyone observe differently?

**Comment by ahmetb** [comment]
@bmhatfield please open a different issue if you're seeing problems.
this issue discusses whether to list installation instructions in the readme or not.

**Comment by jjhuff** [comment]
@ahmetb Once there's some consensus on how to undo/switch to the built in managedcertificate that'd be important to add to the README since a number of people will be in this state.

Also, for issues with ManagedCertificates on GKE, should we open an issue here or engage GCP support in some other way?

**Comment by krzykwas** [comment]
For GKE, the controller installed from this repo can be safely deleted. The CRD installed from this repo does not need to be deleted, because it is automatically overwritten periodically.

You can engage GCP support. Among things that can go wrong it is possible that your DNS configuration is invalid and it is impossible for a CA to create a certificate in such situation. The GCP support will route the issues down to the same team at Google that can respond here.

**Comment by aav7fl** [comment]
> @aav7fl are you having any luck with this? I upgraded and can confirm that `managedcertificates` is available (both in a cluster that never had this deployed, as well as one that did).
> 
> However... nothing happens. The ingress is created, but only with an HTTP frontend. No certificate is obtained, no events are created, the ManagedCertificate doesn't have a status, and there's no indications of errors or progress. It's almost as if the controller isn't running in the cluster.
> 
> Did anyone observe differently?

I'll keep it on track after this comment.

I was able to get the managed certificate created through deploying the yaml file. I set it to a node (manually inside GCP), and then it finished provisioning. I'm just stuck right now getting it to deploy along-side a root certificate signed externally for a seamless rollover.

**Comment by jjhuff** [comment]
@krzykwas Awesome, thanks!

**Comment by Kezzsim** [comment]
I made the mistake of installing this on my GKE cluster,
I've run  : 
`kubectl annotate ingress my-ingress networking.gke.io/managed-certificates-`
`kubectl delete -f deploy/managed-certificate-controller.yaml`
`kubectl delete -f deploy/managedcertificates-crd.yaml`
all commands ran successfully
however, whenever I make a new ingress regardless of name, it instantly gets a bunch of random stuff appended to its annotations and thus stops working, even with HTTP:
`ingress.kubernetes.io/backends: {"k8s-be-30556--6b213e7ef8a48ede":"Unknown","k8s-be-31915--6b213e7ef8a48ede":"Unknown","k8s-be-32710--6b213e7ef8a48ede":"Unknown"}
ingress.kubernetes.io/forwarding-rule: k8s-fw-default-ingress-datalink2--6b213e7ef8a48ede
ingress.kubernetes.io/target-proxy: k8s-tp-default-ingress-datalink2--6b213e7ef8a48ede
ingress.kubernetes.io/url-map: k8s-um-default-ingress-datalink2--6b213e7ef8a48ede
kubernetes.io/ingress.global-static-ip-name: datalink2-ingress
kubectl.kubernetes.io/last-applied-configuration:`

Do I have to destroy the entire cluster and start from scratch now? Where is this hidden service running that's adding all this stuff to my ingresses?

Also, for future advice - I was very happy with the simple routing the built in extensions/v1beta1 Ingress object GKE provided, I didn't want to add another reverse proxy like nginx on top of it just to get SSL/TLS with refreshing certificates. What's the best to use only that and still get SSL so the pages I serve from GKE have encryption?

**Comment by charlex** [comment]
@Kezzsim 

This repo is for the code that is _automatically installed on GKE_. This means you do not have to follow the `README.md` in this repo. 

Instead, if you're a user of GKE follow this [guide](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) which will tell you how to _use_ this pre-installed component.

**Comment by charlex** [comment]
@ahmetb and all: I have added a section in the README for GKE users and filed PR #24 to add this:

```
# Installation on your GKE cluster

If you are a user of GKE (`1.12.6-gke.7` or higher), the managed certificate controlled provided by this repo is already installed for you and ready to be used right now!

You do not have to follow the below steps [Installation on your own cluster on GCP](#installation-on-your-own-cluster-on-gcp). Instead, follow this getting started guide and start using `networking.gke.io/v1beta1` and `ManagedCertificate`.  

# Installation on your own cluster on GCP
```

**Comment by krzykwas** [comment]
This project is developed internally and then the code is pushed to github from an internal Google repo, that is why I can't really apply this change easily - however I recently updated README with the distinction between gke and gcp setup, I also added more info on other things that needed better documentation.

**Comment by ahmetb** [comment]
I recommend we set up copybara or move development to oss.
