### ISSUE TITLE
Wildcard certificate

### ISSUE THREAD

**Issue by mholleville** [GoogleCloudPlatform/gke-managed-certs#20]
Hello ! Just one question support of wildcard certificate is it a feature envisaged?

**Comment by krzykwas** [comment]
Wildcards are on our roadmap, but I'm not allowed to speak about any timelines here.

**Comment by mholleville** [comment]
Thank you. Ingress type GCE can support multiple managed certificate ?

**Comment by krzykwas** [comment]
Correct, you can specify more than one managed certificate per GCE-Ingress.

**Comment by mholleville** [comment]
I see you use Lets encrypt for certificate. Can we specify stagging let's encrypt server ?

We are Google Partner and we used this in front of traefik for an client. This is great work !! Thank you

**Comment by krzykwas** [comment]
That's great to hear, I hope it will be useful to you!

There is no way to change the Let's Encrypt server.

**Comment by nthypes** [comment]
no wildcards yet? it stills on roadmap?

**Comment by krzykwas** [comment]
Currently wildcard certificates are not on a roadmap for this product. We work on wildcard certificates in a different product.
