### ISSUE TITLE
Managed certificate is ignored

### ISSUE THREAD

**Issue by qbast** [GoogleCloudPlatform/gke-managed-certs#21]
Hello 

I created fresh GKE cluster with version 1.12.6-gke.10.
Then I followed the  [howto](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) : creating managedcertificate, service, ingress, external ip and DNS name all worked fine. 
I also verified that domain name resolves to IP of the load balancer.

However after LB is created, nothing happens: kubectl describe managedcertificate shows 'Events: <none> ' .   LB is listening only on port 80. 
Is there any way to debug this?

**Comment by Cidan** [comment]
+1, using GKE 1.12.6-gke.10, the setup instructions [here](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) do not work. The resources are submitted, but the managed cert sits in a perpetually stuck state, with events reading nothing/blank, and no status set. I additionally do not see a managed cert provisioned on GCP it self.

**Comment by qbast** [comment]
I retested it with version 1.12.7-gke.7 . The same problem.

**Comment by krzykwas** [comment]
In GKE we have identified an issue with regional clusters, where managed certificates would behave in the way you've described. Are these regional clusters?

The fix at earliest could be deployed in production at the end of April.

Meanwhile you could deploy the controller from this github repository in your cluster as a mitigation before a fix is deployed.

**Comment by qbast** [comment]
This explains things - all my non-working clusters were regional and the one where it worked was zonal. Thanks for the hint, I will use the controller

**Comment by Cidan** [comment]
Yes, same here. The cluster I'm running are regional. Thanks :)

**Comment by jakebolam** [comment]
This is happening for me to, regional cluster

**Comment by jakebolam** [comment]
The workaround didn't work for us. We've moved back to providing our certs for now.

**Comment by jakebolam** [comment]
The workaround was failing due to https://github.com/GoogleCloudPlatform/gke-managed-certs/issues/18

**Comment by jjhuff** [comment]
@krzykwas Any update on the fix? Users are rather stuck. The built in stuff doesn't work with regional, and this project crash-loops.

**Comment by alexdianomi** [comment]
The thing meant to avoid the matrix from hell, has it's own matrix from hell

**Comment by reynaldiwijaya** [comment]
may i know if there is any timeline for the actual release / implementation in GKE cluster ?

**Comment by matti** [comment]
see https://github.com/GoogleCloudPlatform/gke-managed-certs/issues/18 for update on workaround

**Comment by drewsymo** [comment]
I had this working a few days ago which is really odd.

@qbast I assume you mean 1.12.6-gke.7 for the node versions?

Can't select that version for master from what I can see in GKE.

**Comment by davidgolub** [comment]
I'm having the same issue. This is the error message I get when accessing the https endpoint from the browser. Does someone have a clear workaround I can use?

<img width="970" alt="image" src="https://user-images.githubusercontent.com/12311502/57976087-74e49d80-798d-11e9-9ebf-5850acfc49f0.png">

**Comment by drewsymo** [comment]
That issue tends to resolve itself within 10 minutes of a successful provision.

**Comment by matti** [comment]
yep, sometimes it takes max(10min)

**Comment by rvdh** [comment]
Still experiencing this issue on a regional v1.12.7-gke.10 cluster. @krzykwas any update on when a fix will be deployed?

**Comment by krzykwas** [comment]
The regional cluster issue is fixed in 1.12.7-gke.17 released the previous week.

**Comment by reynaldiwijaya** [comment]
Yeah, upgraded and works smoothly

**Comment by JohannesRudolph** [comment]
Upgrading to 1.12.7-gke.17 worked for me too, however the cert took about 15 minutes to fix SSL protocol errors as descibred by @davidgolub

**Comment by jakebolam** [comment]
Upgraded, and back online. Thanks for getting this done 🙏
