### ISSUE TITLE
Ingress annotation fails

### ISSUE THREAD

**Issue by tarikki** [GoogleCloudPlatform/gke-managed-certs#3]
*Steps to reproduce:*
1. Perform steps 1 and 2 in the instructions.
2.  Create a file for the the managed certificate custom object configuration.
3. Create the managed certificate object from the aforementioned file with the command `kubectl create -f my-managed-cert-object.yaml`
4. Run the command `kubectl annotate ingress [your-ingress-name] gke.googleapis.com/managed-certificates [your-managed-object-name]`.

*Expected Result:*:
Ingress is annotated.

*Actual result:*
kubectl throws the following error: `error: at least one annotation update is required`

**Comment by johnbalvin** [comment]
Did you solve it?

**Comment by tarikki** [comment]
I did ingress annotated with `kubectl annotate ingress [your-ingress-name] gke.googleapis.com/managed-certificates=[your-managed-object-name]`

but then for some reason the gke-managed-certs did not get me a cert. Because I did this on a pre-existing ingress, don't know if it's because the annotation is still wrong or some other setting is preventing it from working, have not had the time for a retry on a completely clean install. If you progress with this let me know :+1:

**Comment by tarikki** [comment]
For another project I followed this tutorial to get renewing certs for kubernetes ingress: https://github.com/ahmetb/gke-letsencrypt

**Comment by krzykwas** [comment]
Hi! As for the initial question, I think the missing equals sign was the reason of the error. Additionally the project is still a pre-alpha work-in-progress and to work properly it needs a [pull request](https://github.com/kubernetes/ingress-gce/pull/508) to ingress to be accepted.
