### ISSUE TITLE
Unable to use TLS 1.3

### ISSUE THREAD

**Issue by gijo-varghese** [GoogleCloudPlatform/gke-managed-certs#33]
The default certificate created uses TLS 1.2. Is there any way to use TLS 1.3? 

TLS 1.3 is much faster and browser support is much better than before

**Comment by krzykwas** [comment]
I believe that the certificate that is provisioned can be used with different versions of TLS protocol, including 1.3. The choice of protocol version should be done on load balancer, though, which in this case is [GKE Ingress](https://github.com/kubernetes/ingress-gce). As far as I know this is usually done via [SSL policies](https://cloud.google.com/load-balancing/docs/ssl-policies-concepts) and most probably TLS 1.3. is not yet supported.

**Comment by gijo-varghese** [comment]
@krzykwas yes, I think TLS 1.3 is not supported yet. Wonder why they're not upgrading it!

**Comment by krzykwas** [comment]
Even though I have been working closely with the team responsible for GKE Ingress, I will not speculate about their priorities, please ask them.

**Comment by gijo-varghese** [comment]
@krzykwas ok. But where can I ask them?

**Comment by krzykwas** [comment]
You could ask on github,  [Ingress GKE](https://github.com/kubernetes/ingress-gce), or through Google support, maybe?
