### ISSUE TITLE
Configure an FQDN for the ingress controller IP address

### ISSUE THREAD

**Issue by nico-kuzak** [GoogleCloudPlatform/gke-managed-certs#37]
Hi, 

Is it possible to configure an FQDN for the ingress controller IP address? I am trying to add https and don't have a domain name to use. For example, on Azure, it is done like this:
https://github.com/Azure/AKS/issues/611#issuecomment-414832826 
and here:
https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip#configure-a-dns-name
and ends up becoming DNSNAME.ZONE.cloudapp.azure.com

Thanks.

**Comment by krzykwas** [comment]
The only way known to me right now is to have a domain name and point it at the IP of your load balancer by making changes to the DNS configuration of your domain. I heard about the thing you've described under the _autodns_ name. It is not supported in GKE as far as I know.
