### ISSUE TITLE
My certificate is in FAILED_RATE_LIMITED status

### ISSUE THREAD

**Issue by mholleville** [GoogleCloudPlatform/gke-managed-certs#40]
Hello ! 

What is the quota on managed SSL certificates?

**Comment by krzykwas** [comment]
FAILED_RATE_LIMITED is a state exposed in the GCLB API. GKE Managed Certificates expose it as FailedRateLimited. This state means that the Certificate Authority did not let you provision another certificate, you were rate limited.

You can:
1) Request fewer certificates and wait to recover the quota.
2) For Let's Encrypt request that they increase the number of certificates that can be provisioned with them for your domain.
3) Allow Google CA (pki.goog) to provision certificates for you with a DNS CAA record, the rate limits are higher than with Let's Encrypt.
