### ISSUE TITLE
Support: What auto installs this?

### ISSUE THREAD

**Issue by rayfoss** [GoogleCloudPlatform/gke-managed-certs#51]
I'm getting bad performance in my cluster from this... It's assuming I use the Google ingress, have port 6443 open, have no cert-manager installed and configured to auto renew le certs and have unlimited google ssl quota... non of that is true.

Is this auto installed by Google? Is this auto installed by gitlab?

**Comment by krzykwas** [comment]
GKE Managed Certs are by default enabled in GKE by Google. How exactly did you reach the conclusion that this feature is negatively affecting the performance?

**Comment by rayfoss** [comment]
I was getting an exponentially increasing amount of error messages in my GKE Activity log. About 100 errors per minute.

The issue turned out to be that cert-manager really needed port 6443 configured and proxied down to the correct pod... I just removed the webhooks version of it, I already have good monitoring of certificate expiration.

**Comment by krzykwas** [comment]
GKE Managed Certs have nothing in common with cert-manager-webhooks. I don't understand the problem well, but it seems it was not caused by GKE Managed Certs.
