### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by jtestard** [GoogleCloudPlatform/gke-managed-certs#54]
The documentation says here that up to 100 domain names can be added:

https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs

Yet is clear from this issue (and my personal experience) that only 1 domain name can be specified:

https://github.com/GoogleCloudPlatform/gke-managed-certs/issues/29

**Comment by krzykwas** [comment]
Just use the v1 API instead of the obsolete v1beta1 version.
