### ISSUE TITLE
Availability in GKE ?

### ISSUE THREAD

**Issue by fproulx-eoscanada** [GoogleCloudPlatform/gke-managed-certs#8]
Hi,
Is this only available on Alpha clusters ? Any idea when it will be more broadly available on Beta/prod clusters?

**Comment by krzykwas** [comment]
The release of managed certificates in GKE will initially be to Alpha clusters. It will be announced through official GKE channels (not here).

The releases to Beta/GA will also be announced through official GKE channels. No promises as to a specific timeline will be given here, sorry.
